### ISSUE TITLE
Please provide updated Thunderbolt NVM (26) on LVFS for XPS 9360

### ISSUE THREAD

**Issue by pachulo** [dell/thunderbolt-nvm-linux#11]
The Thunderbolt NVM on LVFS was last updated in December, and has version 21:

- https://fwupd.org/lvfs/device/dfd51125-338f-56ff-b721-fa3bea8e534e

While the Dell website was updated in April and has a Windows installer for version 26:

- https://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverId=4FC9M

Please provide the updated version on LVFS as well. Thank!

**Comment by superm1** [comment]
@pachulo Here, it's been moved it to testing.  Please give this a try:

https://fwupd.org/lvfs/device/7488415f-8db5-5993-a48e-5a43914afb69

**Comment by pachulo** [comment]
Wow, that was fast! Tested the upgrade and everything went smooth! Here is the report uploaded:

```
Target:                  https://fwupd.org/lvfs/firmware/report
Payload:                 {
                           "ReportVersion" : 2,
                           "MachineId" : "1c424e0553adb374b7285896b4bbb7e8c13ef9915b1d7febb9a9a72b063024fe",
                           "Metadata" : {
                             "DistroId" : "ubuntu",
                             "DistroVersion" : "18.04"
                           },
                           "Reports" : [
                             {
                               "Checksum" : "2e6bff2434b4311010e1d02266da02afaf327d8b",
                               "UpdateState" : 2,
                               "Guid" : "dfd51125-338f-56ff-b721-fa3bea8e534e",
                               "Plugin" : "thunderbolt",
                               "VersionOld" : "21.00",
                               "VersionNew" : "26.01",
                               "Flags" : 35,
                               "Created" : 1531159901,
                               "Modified" : 1531160104,
                               "Metadata" : {
                                 "CpuArchitecture" : "x86_64",
                                 "AppstreamGlibVersion" : "0.7.4",
                                 "KernelVersion" : "4.15.0-23-generic",
                                 "FwupdVersion" : "1.0.6",
                                 "GUsbVersion" : "0.2.11",
                                 "BootTime" : "1531159812",
                                 "ThunderboltNative" : "False"
                               }
                             }
                           ]
                         }
```

Thanks a lot for this!

**Comment by superm1** [comment]
Great, thanks for confirming.  It will stay in testing for a while in case anyone else encounters any problems.

**Comment by superm1** [comment]
Anyone else that encounters this issue before the NVM is promoted, please follow these instructions to turn on LVFS testing.
https://github.com/hughsie/fwupd/wiki/LVFS-Testing-remote

**Comment by frigi83** [comment]
After some days my XPS don't recognize that version 26 installed (message say current version is 00.00) 
[https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1768627](url)

**Comment by ydubreuil** [comment]
Hi,

Would it be possible to provide the same update for Precision 5520 laptop? The NVM 26 firmware is available here: https://www.dell.com/support/home/bg/en/bgdhs1/drivers/driversdetails?driverId=NVNKG 

It doesn't seem to be the same firmware, as both filename and checksum don't match.

**Comment by superm1** [comment]
@frigi83 I've got a potential fix for that issue.  I think it's mostly cosmetic, please reference that bug for more updates on it.

@ydubreuil 
This issue is specifically around the XPS 9360.  Please open new issues for other systems if possible otherwise this is impossible to keep track of.

**Comment by superm1** [comment]
Once this bug migrates to -updates, I think we should release this from -testing.
https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1768627

**Comment by pachulo** [comment]
This is already the case @superm1 ! https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1768627/comments/41

**Comment by pachulo** [comment]
Is there anything preventing this to be migrated to -updates @superm1 ?

**Comment by superm1** [comment]
Thanks for the reminder, it's been migrated now.
