### ISSUE TITLE
Please provide updated Thunderbolt NVM (26) on LVFS for XPS 15 9560/Precision 5520

### ISSUE THREAD

**Issue by ydubreuil** [dell/thunderbolt-nvm-linux#12]
The Thunderbolt NVM on LVFS was last updated in December, and has version 21:

* https://fwupd.org/lvfs/component/342/all

Dell website was updated in April and has a Windows installer for version 26:

* https://www.dell.com/support/home/bg/en/bgdhs1/drivers/driversdetails?driverId=NVNKG

Could you please provide the updated version on LVFS? Thanks!

**Comment by superm1** [comment]
Thanks.  I'll forward this off to the right people.

**Comment by dtzWill** [comment]
Ping! Can you maybe bug them again? Thanks!

**Comment by superm1** [comment]
Sorry, still don't have a CAB available with this built for some reasons I can't share.  For now you can manually download that file, extract it and flash it using `fwupdtool`, or build your own CAB file from https://github.com/hughsie/fwupd/tree/master/contrib/firmware-packager

**Comment by sunnycrown83** [comment]
Version 26 has been pushed.
