### ISSUE TITLE
Please provide updated Thunderbolt NVM (36) for XPS 9575

### ISSUE THREAD

**Issue by rstrube** [dell/thunderbolt-nvm-linux#15]
Hi there!

I noticed that Dell has updated their Thunderbolt firmware for the XPS 9575 to version 36.  See:
https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverId=PR8NR&osCode=WT64A&productCode=xps-15-9575-2-in-1-laptop

Unfortunately this new firmware does not appear in the lvfs *or* lvfs-testing repositories.

Here is my current device details:

```
XPS 9575 Thunderbolt Controller
  DeviceId:             069ac71f347e92d158f2c211cca10d52a19e2d41
  Guid:                 8926f505-8219-5d6c-969a-e927534113fb
  Summary:              Unmatched performance for high-speed I/O
  Plugin:               thunderbolt
  Flags:                internal|updatable|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              30.00
  Icon:                 computer
  Created:              2018-10-24
```
Is there any chance you could add this firmware to lvfs-testing? I'm having problems with getting my eGPU working over TB3, and I'd like to be running the fully updated firmware to rule out any firmware issues that might be causing problems.

Thanks!
Rob

**Comment by superm1** [comment]
Sure, it's in LVFS testing now.

**Comment by rstrube** [comment]
Thanks for the support, really appreciate it.  The update was successful!

```shell
XPS 9575 Thunderbolt Controller
  DeviceId:             069ac71f347e92d158f2c211cca10d52a19e2d41
  Guid:                 8926f505-8219-5d6c-969a-e927534113fb
  Summary:              Unmatched performance for high-speed I/O
  Plugin:               thunderbolt
  Flags:                internal|updatable|supported|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              36.00
  Icon:                 computer
  Created:              2018-10-24
  Modified:             2018-10-24
  UpdateState:          success
```
