### ISSUE TITLE
Missing payload for NVM21 firmware version.

### ISSUE THREAD

**Issue by jpamills** [dell/thunderbolt-nvm-linux#2]
I'm trying to update the NVM firmware on my Dell XPS 13 9360 from version 18.05 to the newest version. I have successfully built everything and am able to enumerate and query the controllers, but I cannot find a payload for the NVM21 firmware version that is available on the Dell website under the name "Intel_TBT3_FW_UPDATE_NVM21_0THFT_A00_3.21.00.008.exe". The payload provided in this repository is the same version as what I have installed currently.

**Comment by lfaraone** [comment]
You can extract them from [Dell's update](http://www.dell.com/support/home/us/en/04/Drivers/DriversDetails?driverId=0THFT) — applied fine on my XPS 9360:

```
$ tbtfwucli GetCurrentNVMVersion $CONTROLLERID
21.00
```

**Comment by BillBillBillBill** [comment]
@lfaraone How to extract files from "Intel_TBT3_FW_UPDATE_NVM21_0THFT_A00_3.21.00.008.exe"?

**Comment by ksfga** [comment]
@BillBillBillBill have you found a way how to extract payload, please?

**Comment by BillBillBillBill** [comment]
@ksfga  use 7z `7z e xxx.EXE`

**Comment by ksfga** [comment]
@BillBillBillBill Thanks.

**Comment by Kegeruneku** [comment]
I see the update contains the following files:
```
0x075B.bin  0x075B_gfx.bin  0x075B_nosecure.bin  0x07BE.bin  0x07BE_gfx.bin  0x07BE_nosecure.bin  0x07BF.bin  0x07BF_gfx.bin  0x07BF_nosecure.bin
```

tbtfwucli seems to accept the 0x075B.bin image (same name as in the payloads folder):
```
16:01 kegeruneku@arkhangelsk ~ % sudo tbtfwucli ValidateFWImage XXXXXXXX 0x075B.bin         
Image validation succeeded.
```

You confirm this is the right image ?

**Comment by jospoortvliet** [comment]
@superm1 thanks for updating the repo. I just ran the update from 18.05 to 21.0 successfully (running openSUSE Tumbleweed here, kernel 4.13.6). Using the 0x075B.bin file. Will do a tiny PR to your readme to help others find out how to figure out which of the two to use  🚀 

Next: to find and fix the cause of my network drops 🎸
