### ISSUE TITLE
Missing NVM46 (K3D5D) 4.46.110.006 for Precision Mobile 5540

### ISSUE THREAD

**Issue by arcivanov** [dell/thunderbolt-nvm-linux#28]
Subj. The Windows-based `Intel_TBT3_FW_UPDATE_NVM46_K3D5D_A03_4.46.110.006` has been available for a while and is marked *urgent*.

**Comment by arcivanov** [comment]
@superm1 TIA!

**Comment by superm1** [comment]
> @superm1 TIA!

You can check with @dell-client-linux

**Comment by arcivanov** [comment]
@dell-client-linux, can you help?

**Comment by arcivanov** [comment]
@superm1 anybody else can help with this? It's a security update and I'd like to be able to install it.

**Comment by superm1** [comment]
Sorry, I'm not with Dell anymore. @dell-client-linux is your best bet.

**Comment by sunnycrown83** [comment]
@arcivanov We will take this and check with internal about the NVM46 for Linux.

**Comment by arcivanov** [comment]
Thank you @sunnycrown83

**Comment by arcivanov** [comment]
@sunnycrown83 any news?

**Comment by sunnycrown83** [comment]
@arcivanov We have figured out the problem and the FW is under testing under Linux before we promote it out. I assume it will take 1-2 weeks to complete it.

**Comment by arcivanov** [comment]
Excellent!!! Thank you!

**Comment by sunnycrown83** [comment]
Forget to mention is Oct 1~7 is National Day Holiday in China, if we can't make it before Oct, please expect the week after the holiday.

**Comment by sunnycrown83** [comment]
NVM46 for 5540 has been promoted.

**Comment by arcivanov** [comment]
Thanks! Installed and applied correctly.
