### ISSUE TITLE
Interops issue Dell Precision 7510 / WD22TB4 / Linux Kernel (4.15 through 5.19)

### ISSUE THREAD

**Issue by istr** [dell/thunderbolt-nvm-linux#32]
Hello @superm1,
being totally aware that this is not exactly the right place to put it, I will try my luck anyway, because I did not find a better place.

**Situation**
Dell Precision 7510, Latitude 7420, U3818DW, WD22TB4. I bought the latter, because it was advertised to gracefully fall back to WD19 behavior with TB3. Which it does, but only with Windows.

**What works**
- Windows 10: 7510 + Dock + Display + USB in Dock + Network in Dock
- Windows 10: 7420 + Dock + Display + USB in Dock + Network in Dock
- Ubuntu 22.04.1 LTS: 7510 + Dock + Display
- Ubuntu 22.04.1 LTS: 7420 + Dock + Display + USB in Dock + Network in Dock

**What does NOT work**
- USB xhci controller in Dock (and thus: Network in Dock) with 7510 and linux

Obviously this is NOT a problem with the firmware (everything is on the latest version), because 7510 with Win10 works like a charm, but fails with Ubuntu (and other linux distributions and several kernels).

I tried different kernels with the 7510 (4.15.0 - Ubuntu 18, 5.8 - Ubuntu 20, 5.15 - Ubuntu 22, 5.19 FC37 beta).
All fail with the same symptom during the xhci_hcd initialization phase.

I will proceed with what I saw under these circumstances:
```
lsb_release -d
Description: Ubuntu 22.04.1 LTS
uname -vir
5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64
```
The difference between 7510 and 7420 (same Ubuntu 22 live USB stick) is that the same kernel passes the xhci_hcd initialization for the 7420. All attached devices (even those attached to the U3818DW) then show up using `lsusb` and are fully usable.

For the 7510 the kernel detects the xhci_hcd controller, starts the initialization and then bails out after about 10 seconds.

```
root@ubuntu:/home/ubuntu# dmesg | grep xhci | grep :09
[    1.738095] xhci_hcd 0000:09:00.0: xHCI Host Controller
[    1.738100] xhci_hcd 0000:09:00.0: new USB bus registered, assigned bus number 3
[    1.739677] xhci_hcd 0000:09:00.0: hcc params 0x20007fc1 hci version 0x110 quirks 0x0000000000009810
[    1.740437] xhci_hcd 0000:09:00.0: xHCI Host Controller
[    1.740442] xhci_hcd 0000:09:00.0: new USB bus registered, assigned bus number 4
[    1.740445] xhci_hcd 0000:09:00.0: Host supports USB 3.1 Enhanced SuperSpeed
[   12.039414] xhci_hcd 0000:09:00.0: Abort failed to stop command ring: -110
[   12.039489] xhci_hcd 0000:09:00.0: xHCI host controller not responding, assume dead
[   12.039525] xhci_hcd 0000:09:00.0: HC died; cleaning up
[   12.039587] xhci_hcd 0000:09:00.0: Error while assigning device slot ID
[   12.039691] xhci_hcd 0000:09:00.0: Max number of devices this xHCI host supports is 64.
[ 2878.324418] xhci_hcd 0000:09:00.0: remove, state 1
[ 2878.324893] xhci_hcd 0000:09:00.0: USB bus 4 deregistered
[ 2878.324911] xhci_hcd 0000:09:00.0: remove, state 1
[ 2878.325310] xhci_hcd 0000:09:00.0: Host halt failed, -19
[ 2878.325319] xhci_hcd 0000:09:00.0: Host not accessible, reset failed.
[ 2878.325508] xhci_hcd 0000:09:00.0: USB bus 3 deregistered
[ 3610.439220] xhci_hcd 0000:09:00.0: xHCI Host Controller
[ 3610.439226] xhci_hcd 0000:09:00.0: new USB bus registered, assigned bus number 3
[ 3610.440427] xhci_hcd 0000:09:00.0: hcc params 0x20007fc1 hci version 0x110 quirks 0x0000000000009810
[ 3610.441320] xhci_hcd 0000:09:00.0: xHCI Host Controller
[ 3610.441324] xhci_hcd 0000:09:00.0: new USB bus registered, assigned bus number 4
[ 3610.441328] xhci_hcd 0000:09:00.0: Host supports USB 3.1 Enhanced SuperSpeed
[ 3620.871445] xhci_hcd 0000:09:00.0: Abort failed to stop command ring: -110
[ 3620.871458] xhci_hcd 0000:09:00.0: xHCI host controller not responding, assume dead
[ 3620.871461] xhci_hcd 0000:09:00.0: HC died; cleaning up
[ 3620.871506] xhci_hcd 0000:09:00.0: Error while assigning device slot ID
[ 3620.871531] xhci_hcd 0000:09:00.0: Max number of devices this xHCI host supports is 64.
```

The same happens when unbinding / binding the controller using
```
echo -n "0000:09:00.0" > /sys/bus/pci/drivers/xhci_hcd/unbind
echo -n "0000:09:00.0" > /sys/bus/pci/drivers/xhci_hcd/bind
```
or when unplugging / plugging the dock and the 7510 (you can see an unplug/plug event in the dmesg above).

I suggest that there seems to be a problem with the handshake and/or power management that goes wrong between the `Alpine Ridge 2C 2015` and the `Goshen Ridge 2020`. Again - the Windows 10 driver is fully capable of handling this, whereas the xhci_hcd module in the kernel fails.

When using kernel debugging it turns out that this `FIXME` in the kernel source gets triggered:
https://github.com/torvalds/linux/blob/e8bc52cb8df80c31c73c726ab58ea9746e9ff734/drivers/usb/host/xhci.c#L2979 

Adding some "quirks" to the device in question using `usbcore.quirks=...:...:bgk` as per https://docs.kernel.org/next/admin-guide/kernel-parameters.html did not help either.

Do you have any idea where to look or to ask?
Could you imagine that a "downgrade" of the dock using a WD19 connector could help?

**Comment by superm1** [comment]
I'm no longer with Dell.  A few ideas for you:

1)  Reach out to Dell support.  
2)  Try to raise it through https://launchpad.net/dell
1) @dell-client-linux might be able to help.
2)  You can try to raise it with  https://bugzilla.kernel.org/ You probably want to try to reproduce with kernel 6.0 before raising it there though.

**Comment by CragW** [comment]
See if this helps you to address the xhci host controller issue.
https://github.com/torvalds/linux/commit/09f736aa95476631227d2dc0e6b9aeee1ad7ed58

It's worthwhile to try Ubuntu 22.10 with kernel 5.19.0-21.21.
https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/kinetic/log/drivers/usb/host/xhci-ring.c

**Comment by istr** [comment]
@superm1 @CragW Thanks a lot for the hints. I will close this issue. TBH I do not really expect Dell support to resolve the issue, as the failing machine is EOL. The bar to file this to upstream kernel is high, but I will try to address it there anyway.

**Comment by istr** [comment]
@CragW just for the record - same effect with Ubuntu 22.10 / 5.19.0-21.21 so there must be something else going on here.

**Comment by CragW** [comment]
hmm.. it's odd. Maybe a different case on your end from the patch at https://lore.kernel.org/all/8c3cd8f7-0bd1-0ec4-2f58-6122ae7ef270@linux.intel.com/ that requires further discussion with upstream.

**Comment by istr** [comment]
Same with 6.0.3 from https://kernel.ubuntu.com/~kernel-ppa/mainline/ and with an OEM kernel for 22.04 LTS.
I will try to compile a kernel with this patch reverted or find an older kernel without that patch.

**Comment by istr** [comment]
@CragW Just for the record - the problem persists up to 6.2.2 (from https://kernel.ubuntu.com/~kernel-ppa/mainline/) and the kernel from `linux-oem-22.04c`. With newer kernels and some more logging I see lots of ACPI and BAR problems in dmesg.

Some more observations:
- `boltctl` is able to see the dock
- `lspci` sees the pci bridge(s) when the dock is plugged
- `fwupd` can only see the USB4 controller through the `thunderbolt` plugin
- `fwupd` fails to show the dock using the `dell-dock` plugin (none of the parts are detected)

Maybe there is an issue with the usb4 -> xhci fallback code as well...
