### ISSUE TITLE
Cannot update XPS 13 9360 Thunderbolt Controller

### ISSUE THREAD

**Issue by benruijl** [dell/thunderbolt-nvm-linux#4]
I cannot update the thunderbolt firmware if I follow the instructions on the [Arch wiki page](https://wiki.archlinux.org/index.php/Dell_XPS_13_(9360)).

- The forcing works ( `./force_dell_tbt 1`)
- Triggering the update does not make the screen flicker
- `cat /sys/bus/thunderbolt/devices/0-0/nvm_authenticate` returns 0
- `cat /sys/bus/thunderbolt/devices/0-0/nvm_version` returns 18.5 (nothing changed)

My `journalctl` recorded a lot of errors: [bug.txt](https://github.com/dell/thunderbolt-nvm-linux/files/1390509/bug.txt)

**Comment by superm1** [comment]
Was this system purchased with Ubuntu?  I'm suspecting no, and also that you have a different system ID than the XPS 9360 supported by this project.  You can confirm by checking `# smbios-sys-info `and sharing the System ID.  The binary in this project supports `0x075B`.  I'm guessing you have `0x082A`.

If my suspicion is correct then you'll need to extract the right one for your system ID from here: http://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverId=MHTHF

**Comment by benruijl** [comment]
Actually, mine did come pre-installed with Ubuntu and my ID is `0x075B`.

**Comment by superm1** [comment]
OK, that's good to hear.
Can you try the `0x075B` binary in the same Dell support link I provided rather than the one on this repository?

FYI, flickering screen isn't necessarily going to happen.

**Comment by benruijl** [comment]
That one worked!

**Comment by superm1** [comment]
Great!
