### ISSUE TITLE
Failed to update thunderbolt firmware on Dell XPS 13 9360

### ISSUE THREAD

**Issue by fentensoft** [dell/thunderbolt-nvm-linux#6]
I'm rung Archlnux on my Dell XPS 13 9360 with kernel 4.13.9, and I followed the steps in this page:  [Archlinux Wiki](https://wiki.archlinux.org/index.php/Dell_XPS_13_(9360)#Thunderbolt_Firmware_updates), to update my thunderbolt firmware from 18.5 to 21.0. But I got this problem

`bash: /sys/bus/thunderbolt/devices/0-0/nvm_authenticate: Permission denied`

I'm running these commands under root user. I've tried 0x075B_secure.bin extracted from the latest .exe file, but it still doesn't work. Could someone give me some help?

**Comment by superm1** [comment]
Try setting authorized to 1 first

**Comment by fentensoft** [comment]
Still got permission denied error.

`zsh: permission denied: /sys/bus/thunderbolt/devices/0-0/authorized`

**Comment by superm1** [comment]
As root that failed? Can you check dmesg for errors?

What's the exact command you were using to set to 1?

**Comment by fentensoft** [comment]
I used the following comming:
` sudo echo 1 > /sys/bus/thunderbolt/devices/0-0/authorized`
I rebooted the system, and login as root directly, then it worked. It's weird, but thanks. :+1:

**Comment by superm1** [comment]
`sudo echo 1` doesn't write as root, that writes as user.  
It needs to be `"echo 1" | sudo tee /sys/bus/thunderbolt/devices/0-0/authorized` to write as root

**Comment by fentensoft** [comment]
I see, thanks.

**Comment by srgzx** [comment]
Having a similar problem

As root, "echo 1 > authorized" results in bash: echo: write error: Invalid argument

I can dd the firmware to the nvm_non_active0 no problem, but can't get it actually loaded 

"echo 1 > nvm_authenticate" gives the exact same error, bash: echo: write error: Invalid argument

I don't see anything show up in demesg 

I assume I am doing something really really stupid here, but I just can't seem to figure out what's wrong 🤷‍♂️
